---
title: "Update_flashier_F.Rmd"
output: pdf_document
date: "2024-12-10"
---

```{r}
library(flashier)
library(devtools)
load_all()
library(flashierX)
```

```{r}
# taken from
# https://github.com/stephenslab/drift.alpha/blob/master/R/simulate.R
two_pop_tree_sim <- function(n_per_pop, p, sigma_e, sigma_b=rep(1, 3)){

  if(length(sigma_b) != 3){
    stop("There can only be 3 branch lengths i.e. factors")
  }

  # number of individuals
  n <- n_per_pop * 2

  # loadings matrix which specifies the topology
  L <- matrix(0, nrow=n, ncol=3)
  L[ ,1] <- 1
  L[1:n_per_pop, 2] <- 1
  L[(n_per_pop + 1):(2 * n_per_pop), 3] <- 1

  # drift on each branch
  F <- matrix(NA, nrow=p, ncol=3)
  for(k in 1:3){
    F[ ,k] <- rnorm(p, 0, sigma_b[k])
  }

  # errors
  E <- matrix(rnorm(n*p, 0, sigma_e), nrow=n, ncol=p)

  # data
  Y <- L %*% t(F) + E

  # simulation object
  res <- list(Y=Y, L=L, F=F)
  return(res)

}
```

```{r}
set.seed(235)
n_per_pop <- 50
pops <- c(rep("Pop1", n_per_pop), rep("Pop2", n_per_pop))
sigma_e <- 1.0
sigma_b <- c(1.0, 1.0, 1.0)
p = 100
sim_res <- two_pop_tree_sim(n_per_pop, p, sigma_e, sigma_b)
```

```{r}
flash_obj <- flash(sim_res$Y, ebnm_fn = ebnm_point_normal, greedy_Kmax = 10)
flash_obj2 <- update_flashier_F(flash_obj)
```
This results in that the posterior variances are the same for each column of F.

```{r}
flash_obj2$flash_fit$EF2[[2]] - flash_obj2$flash_fit$EF[[2]]^2
```
